name: UnraveledMCMod
main: me.unraveledmc.unraveledmcmod.UnraveledMCMod
version: 2.0
description: Plugin for the UnraveledMC server.
depend: [Aero]
softdepend: [BukkitTelnet, UMC-Essentials, LibsDisguises, DiscordSRV, WorldEdit]
authors: [Madgeek1450, Prozza, CreeperSeth, AwesomePinch, aggelosQQ, RobinGall2910]
